---
- name: Add node.master as true for master node
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: "node.master:"
    line: 'node.master: true'

- name: Add node.data as false, master
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: "node.data:"
    line: 'node.data: false'
  
- name: Add node.ingest as false, master
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: "node.ingest:"
    line: 'node.ingest: false'

# - name: Add attr rack
#   lineinfile:
#     destfile: /etc/elasticsearch/elasticsearch.yml
#     regexp: "node.attr.rack:"
#     line: 'node.attr.zone: 1'
  # notify: Starting Elasticsearch
